name: Bug Report
description: Report an unexpected behavior or an error.
title: '[BUG] '
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you're experiencing.
      placeholder: Example — When trying to save, I receive a 500 error.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps needed to reproduce the issue.
      placeholder: |
        1. Go to page X
        2. Click on button Y
        3. Observe the error
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Example — The page should load successfully.
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: Example — Chrome 125 / macOS / Staging