spring:
  application:
    name: order-service
  liquibase:
    change-log: classpath:/liquibase/master.xml
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:orders}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  rabbitmq:
    port: 5672
    stream:
      username: ${RABBITMQ_USER:guest}
      password: ${RABBITMQ_PASS:guest}
      host: ${RABBITMQ_HOST:localhost}
springdoc:
  api-docs:
    path: /api-docs